spring:
  security:
    user:
      name: user
      password: user
  application:
    name: Shop
  datasource:
    url: jdbc:h2:file:./src/main/resources/dbase
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: never
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: false
